---
  - name: Add Elastic GPG Key
    apt_key:
      url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
      state: present
  - name: Add Elastic repository
    apt_repository:
      repo: "deb https://artifacts.elastic.co/packages/{{ elasticsearch_version }}/apt stable main"
      state: present
      update_cache: yes
  - name: Install Metricbeat
    apt:
      name: metricbeat
      state: latest
  - name: Add confiration files
    copy:
      src: 'files/etc/'
      dest: '/etc/'
  - name: Add confiration files
    template:
      src: 'files/etc/metricbeat/metricbeat.yml'
      dest: '/etc/metricbeat/metricbeat.yml'
  - name: Restart metricbeat
    service:
      name: metricbeat
      state: restarted
